spring:
  h2:
    console:
      enabled: true
  datasource:
    username: svc_local
    password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:local
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true
