spring:
  datasource:
    username: svc_production
    password: K4fJDVwhNiD6Mjoy
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wanted
  jpa:
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
