version: '3.1'

services:
  db:
    image: mysql:8.0
    platform: linux/amd64
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: svc_production
      MYSQL_PASSWORD: K4fJDVwhNiD6Mjoy
      MYSQL_DATABASE: wanted
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
      - --skip-character-set-client-handshake  # client charset -> server charset으로 설정
