###
POST http://localhost:8080/recruitment/v1
Content-Type: application/json

{
  "company_id": 1,
  "position": "백엔드 주니어 개발자",
  "reward": 1000000,
  "description": "원티드래에서 백엔드 주니어 개발자를 채용합니다. 자격요건은..",
  "skill": "Python"
}

### 채용보상금, 채용내용 변경 (채용공고 등록 후 요청)
PUT http://localhost:8080/recruitment/v1
Content-Type: application/json

{
  "recruitmentId": 1,
  "position": "백엔드 주니어 개발자",
  "reward": 1500000,
  "description": "원티드랩에서 백엔드 주니어 개발자를 '적극' 채용합니다. 자격요건은..",
  "skill": "Python"
}

### 사용기술 변경
PUT http://localhost:8080/recruitment/v1
Content-Type: application/json

{
  "recruitmentId": 1,
  "position": "백엔드 주니어 개발자",
  "reward": 1000000,
  "description": "원티드랩에서 백엔드 주니어 개발자를 채용합니다. 자격요건은..",
  "skill": "Django"
}
